import type { ThemeConfig } from "@/themes/engine/types";

const FRAUNCES = "'Fraunces', Georgia, 'Times New Roman', serif";
const MARCELLUS = "'Marcellus', 'Palatino Linotype', Palatino, Georgia, serif";
const BRICOLAGE = "'Bricolage Grotesque', 'Avenir Next', 'Segoe UI', system-ui, sans-serif";
const JAKARTA = "'Plus Jakarta Sans', system-ui, -apple-system, 'Segoe UI', sans-serif";
const INTER = "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif";

export const KULINER_THEMES: Record<string, ThemeConfig> = {
  hangat: {
    slug: "hangat",
    name: "Hangat",
    character: "Earth tone membumi — warung & rumah makan keluarga",
    colors: {
      bg: "#FFFBF5",
      surface: "#FFFFFF",
      text: "#2D2A26",
      muted: "#6B655E",
      primary: "#C4501B",
      primaryContrast: "#FFFFFF",
      accent: "#E8A03C",
      heroOverlay: "linear-gradient(180deg, rgb(30 16 6 / 0.15) 0%, rgb(30 16 6 / 0.72) 82%)",
      heroBg: "linear-gradient(150deg, #FFF3E2 0%, #FFE1C2 55%, #F6C08E 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "photo", menu: "cards" },
  },
  arang: {
    slug: "arang",
    name: "Arang",
    character: "Gelap elegan berlapis emas — grill, kopi & dining malam",
    colors: {
      bg: "#15130F",
      surface: "#1F1B15",
      text: "#EDE6DA",
      muted: "#A89F93",
      primary: "#C9A227",
      primaryContrast: "#171310",
      accent: "#8A9B7C",
      heroOverlay: "linear-gradient(180deg, rgb(10 8 5 / 0.3) 0%, rgb(10 8 5 / 0.82) 85%)",
      heroBg:
        "radial-gradient(50rem 30rem at 80% -10%, rgb(201 162 39 / 0.16), transparent 60%), linear-gradient(170deg, #1B1813 0%, #15130F 100%)",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "typo", menu: "list" },
  },
  ceria: {
    slug: "ceria",
    name: "Ceria",
    character: "Cerah playful — kedai kekinian, dessert & minuman",
    colors: {
      bg: "#FFFDF7",
      surface: "#FFFFFF",
      text: "#27221C",
      muted: "#7A7168",
      primary: "#FF6B57",
      primaryContrast: "#2A1712",
      accent: "#4ECDC4",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 24rem at 90% 10%, rgb(78 205 196 / 0.35), transparent 60%), radial-gradient(28rem 28rem at 5% 90%, rgb(255 209 102 / 0.4), transparent 55%), #FF6B57",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "1.4rem", button: "9999px" },
    layout: { hero: "color-block", menu: "grid-2" },
  },
  kopi: {
    slug: "kopi",
    name: "Kopi",
    character: "Monokrom krem-espresso — coffee shop minimal",
    colors: {
      bg: "#F5F0E8",
      surface: "#FFFFFF",
      text: "#2B241D",
      muted: "#8A7E70",
      primary: "#4A3428",
      primaryContrast: "#F5F0E8",
      accent: "#C89F7B",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #EFE7DA 0%, #E2D5C2 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.6rem", button: "0.6rem" },
    layout: { hero: "typo", menu: "cards" },
  },
  senja: {
    slug: "senja",
    name: "Senja",
    character: "Gradasi matahari terbenam — cafe rooftop & outdoor",
    colors: {
      bg: "#FFF9F4",
      surface: "#FFFFFF",
      text: "#33222B",
      muted: "#8A6E7C",
      primary: "#B23A5E",
      primaryContrast: "#FFFFFF",
      accent: "#FFB25E",
      heroOverlay: "none",
      heroBg: "linear-gradient(160deg, #FFB25E 0%, #E86A8A 55%, #6D4B8A 130%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  padi: {
    slug: "padi",
    name: "Padi",
    character: "Hijau-emas tradisional — masakan Padang & nusantara",
    colors: {
      bg: "#F7F8F2",
      surface: "#FFFFFF",
      text: "#24301F",
      muted: "#6F7A68",
      primary: "#2F6B3A",
      primaryContrast: "#FFFFFF",
      accent: "#C9A227",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(40rem 24rem at 85% -5%, rgb(201 162 39 / 0.22), transparent 60%), linear-gradient(165deg, #EDF2E2 0%, #DDE8CC 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.8rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "list" },
  },
  laut: {
    slug: "laut",
    name: "Laut",
    character: "Biru laut segar — seafood & ikan bakar",
    colors: {
      bg: "#F3FAFB",
      surface: "#FFFFFF",
      text: "#15303B",
      muted: "#5E7E8A",
      primary: "#0E7490",
      primaryContrast: "#FFFFFF",
      accent: "#5EEAD4",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 90% 0%, rgb(94 234 212 / 0.3), transparent 55%), linear-gradient(165deg, #E3F4F7 0%, #C7E8EE 100%)",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 700 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  manis: {
    slug: "manis",
    name: "Manis",
    character: "Pastel lembut membulat — bakery, kue & dessert box",
    colors: {
      bg: "#FFF7F9",
      surface: "#FFFFFF",
      text: "#3A2E33",
      muted: "#95818A",
      primary: "#C2517F",
      primaryContrast: "#FFFFFF",
      accent: "#B5E3D8",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 26rem at 12% 10%, rgb(181 227 216 / 0.5), transparent 55%), linear-gradient(160deg, #FFE9F0 0%, #F8D7E4 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.6rem", button: "9999px" },
    layout: { hero: "typo", menu: "grid-2" },
  },
  sambal: {
    slug: "sambal",
    name: "Sambal",
    character: "Merah berani tipografi tebal — ayam geprek & pedas-pedasan",
    colors: {
      bg: "#FFF8F4",
      surface: "#FFFFFF",
      text: "#261312",
      muted: "#7D615C",
      primary: "#B3261E",
      primaryContrast: "#FFFFFF",
      accent: "#FFC53D",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 26rem at 88% 12%, rgb(255 197 61 / 0.4), transparent 55%), #B3261E",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "0.9rem", button: "0.6rem" },
    layout: { hero: "color-block", menu: "grid-2" },
  },
  kebun: {
    slug: "kebun",
    name: "Kebun",
    character: "Hijau daun natural ringan — healthy food, salad & jus",
    colors: {
      bg: "#F6FBF4",
      surface: "#FFFFFF",
      text: "#233324",
      muted: "#6C7F6C",
      primary: "#3E7C4F",
      primaryContrast: "#FFFFFF",
      accent: "#D9E8C5",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 22rem at 8% 0%, rgb(217 232 197 / 0.6), transparent 60%), linear-gradient(165deg, #EAF5E4 0%, #D8ECD2 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.2rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  batik: {
    slug: "batik",
    name: "Batik",
    character: "Editorial heritage berpola — resto nusantara & katering hajatan",
    colors: {
      bg: "#FAF6EE",
      surface: "#FFFFFF",
      text: "#2A2118",
      muted: "#7C6F5E",
      primary: "#3F4C8A",
      primaryContrast: "#FFFFFF",
      accent: "#B98A2F",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(circle at 12% 20%, rgb(185 138 47 / 0.14) 0 18%, transparent 19%), radial-gradient(circle at 88% 75%, rgb(63 76 138 / 0.1) 0 22%, transparent 23%), linear-gradient(170deg, #F5EEDD 0%, #EFE5CE 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 550 },
    radius: { card: "0.5rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "magazine" },
    flair: "batik",
  },
  neon: {
    slug: "neon",
    name: "Neon",
    character: "Gelap menyala khas street food malam — burger, ramen & nongkrong",
    colors: {
      bg: "#0B0B12",
      surface: "#15151F",
      text: "#EDEDF7",
      muted: "#8E8EA6",
      primary: "#FF3D8A",
      primaryContrast: "#FFFFFF",
      accent: "#22D3EE",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(34rem 22rem at 85% -5%, rgb(255 61 138 / 0.25), transparent 60%), radial-gradient(30rem 20rem at 5% 100%, rgb(34 211 238 / 0.18), transparent 55%), #0B0B12",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "poster", menu: "cards" },
    flair: "neon",
  },
  pasar: {
    slug: "pasar",
    name: "Pasar",
    character: "Pop berani ala poster pasar — gerobak, jajanan & franchise lokal",
    colors: {
      bg: "#FFD335",
      surface: "#FFFFFF",
      text: "#161311",
      muted: "#5C5344",
      primary: "#161311",
      primaryContrast: "#FFD335",
      accent: "#FF5CA8",
      heroOverlay: "none",
      heroBg: "#FFD335",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "color-block", menu: "polaroid" },
    flair: "brutal",
  },
  kertas: {
    slug: "kertas",
    name: "Kertas",
    character: "Minimal tenang berbingkai — omakase, teh & fine dining kecil",
    colors: {
      bg: "#FBFAF7",
      surface: "#FFFFFF",
      text: "#26241F",
      muted: "#8B857A",
      primary: "#8C2F2F",
      primaryContrast: "#FBFAF7",
      accent: "#C9C2B2",
      heroOverlay: "none",
      heroBg: "#FBFAF7",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.15rem", button: "0.15rem" },
    layout: { hero: "frame", menu: "list" },
    flair: "zen",
  },
  tropis: {
    slug: "tropis",
    name: "Tropis",
    character: "Resort hijau-mangga dengan lengkung — jus bar, poke & brunch",
    colors: {
      bg: "#FBF7EC",
      surface: "#FFFFFF",
      text: "#1D3524",
      muted: "#647A69",
      primary: "#14532D",
      primaryContrast: "#F6FBEF",
      accent: "#F5A623",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 26rem at 90% 8%, rgb(245 166 35 / 0.25), transparent 55%), linear-gradient(160deg, #EFF6E4 0%, #DDEDD2 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 650 },
    radius: { card: "1.5rem", button: "9999px" },
    layout: { hero: "split", menu: "grid-2" },
    flair: "tropis",
  },
};

export const DEFAULT_THEME = "hangat";

export function themeConfigFor(slug: string): ThemeConfig {
  return KULINER_THEMES[slug] ?? (KULINER_THEMES[DEFAULT_THEME] as ThemeConfig);
}
