import type { ThemeConfig } from "@/themes/engine/types";

const FRAUNCES = "'Fraunces', Georgia, 'Times New Roman', serif";
const MARCELLUS = "'Marcellus', 'Palatino Linotype', Palatino, Georgia, serif";
const BRICOLAGE = "'Bricolage Grotesque', 'Avenir Next', 'Segoe UI', system-ui, sans-serif";
const JAKARTA = "'Plus Jakarta Sans', system-ui, -apple-system, 'Segoe UI', sans-serif";
const INTER = "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif";

export const KULINER_THEMES: Record<string, ThemeConfig> = {
  hangat: {
    slug: "hangat",
    name: "Hangat",
    character: "Earth tone membumi — warung & rumah makan keluarga",
    tags: ["terang", "earth", "klasik", "foto", "keluarga"],
    colors: {
      bg: "#FFFBF5",
      surface: "#FFFFFF",
      text: "#2D2A26",
      muted: "#6B655E",
      primary: "#C4501B",
      primaryContrast: "#FFFFFF",
      accent: "#E8A03C",
      heroOverlay: "linear-gradient(180deg, rgb(30 16 6 / 0.15) 0%, rgb(30 16 6 / 0.72) 82%)",
      heroBg: "linear-gradient(150deg, #FFF3E2 0%, #FFE1C2 55%, #F6C08E 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "photo", menu: "cards" },
  },
  arang: {
    slug: "arang",
    name: "Arang",
    character: "Gelap elegan berlapis emas — grill, kopi & dining malam",
    tags: ["gelap", "mewah", "klasik", "emas", "malam"],
    colors: {
      bg: "#15130F",
      surface: "#1F1B15",
      text: "#EDE6DA",
      muted: "#A89F93",
      primary: "#C9A227",
      primaryContrast: "#171310",
      accent: "#8A9B7C",
      heroOverlay: "linear-gradient(180deg, rgb(10 8 5 / 0.3) 0%, rgb(10 8 5 / 0.82) 85%)",
      heroBg:
        "radial-gradient(50rem 30rem at 80% -10%, rgb(201 162 39 / 0.16), transparent 60%), linear-gradient(170deg, #1B1813 0%, #15130F 100%)",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "typo", menu: "list" },
  },
  ceria: {
    slug: "ceria",
    name: "Ceria",
    character: "Cerah playful — kedai kekinian, dessert & minuman",
    tags: ["terang", "playful", "modern", "warna", "kekinian"],
    colors: {
      bg: "#FFFDF7",
      surface: "#FFFFFF",
      text: "#27221C",
      muted: "#7A7168",
      primary: "#FF6B57",
      primaryContrast: "#2A1712",
      accent: "#4ECDC4",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 24rem at 90% 10%, rgb(78 205 196 / 0.35), transparent 60%), radial-gradient(28rem 28rem at 5% 90%, rgb(255 209 102 / 0.4), transparent 55%), #FF6B57",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "1.4rem", button: "9999px" },
    layout: { hero: "color-block", menu: "grid-2" },
  },
  kopi: {
    slug: "kopi",
    name: "Kopi",
    character: "Monokrom krem-espresso — coffee shop minimal",
    tags: ["terang", "minimal", "kopi", "earth", "klasik"],
    colors: {
      bg: "#F5F0E8",
      surface: "#FFFFFF",
      text: "#2B241D",
      muted: "#8A7E70",
      primary: "#4A3428",
      primaryContrast: "#F5F0E8",
      accent: "#C89F7B",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #EFE7DA 0%, #E2D5C2 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.6rem", button: "0.6rem" },
    layout: { hero: "typo", menu: "cards" },
  },
  senja: {
    slug: "senja",
    name: "Senja",
    character: "Gradasi matahari terbenam — cafe rooftop & outdoor",
    tags: ["terang", "gradasi", "romantis", "modern"],
    colors: {
      bg: "#FFF9F4",
      surface: "#FFFFFF",
      text: "#33222B",
      muted: "#8A6E7C",
      primary: "#B23A5E",
      primaryContrast: "#FFFFFF",
      accent: "#FFB25E",
      heroOverlay: "none",
      heroBg: "linear-gradient(160deg, #FFB25E 0%, #E86A8A 55%, #6D4B8A 130%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  padi: {
    slug: "padi",
    name: "Padi",
    character: "Hijau-emas tradisional — masakan Padang & nusantara",
    tags: ["terang", "tradisional", "hijau", "emas", "nusantara"],
    colors: {
      bg: "#F7F8F2",
      surface: "#FFFFFF",
      text: "#24301F",
      muted: "#6F7A68",
      primary: "#2F6B3A",
      primaryContrast: "#FFFFFF",
      accent: "#C9A227",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(40rem 24rem at 85% -5%, rgb(201 162 39 / 0.22), transparent 60%), linear-gradient(165deg, #EDF2E2 0%, #DDE8CC 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.8rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "list" },
  },
  laut: {
    slug: "laut",
    name: "Laut",
    character: "Biru laut segar — seafood & ikan bakar",
    tags: ["terang", "biru", "segar", "modern", "seafood"],
    colors: {
      bg: "#F3FAFB",
      surface: "#FFFFFF",
      text: "#15303B",
      muted: "#5E7E8A",
      primary: "#0E7490",
      primaryContrast: "#FFFFFF",
      accent: "#5EEAD4",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 90% 0%, rgb(94 234 212 / 0.3), transparent 55%), linear-gradient(165deg, #E3F4F7 0%, #C7E8EE 100%)",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 700 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  manis: {
    slug: "manis",
    name: "Manis",
    character: "Pastel lembut membulat — bakery, kue & dessert box",
    tags: ["terang", "pastel", "lembut", "manis", "bakery"],
    colors: {
      bg: "#FFF7F9",
      surface: "#FFFFFF",
      text: "#3A2E33",
      muted: "#95818A",
      primary: "#C2517F",
      primaryContrast: "#FFFFFF",
      accent: "#B5E3D8",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 26rem at 12% 10%, rgb(181 227 216 / 0.5), transparent 55%), linear-gradient(160deg, #FFE9F0 0%, #F8D7E4 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.6rem", button: "9999px" },
    layout: { hero: "typo", menu: "grid-2" },
  },
  sambal: {
    slug: "sambal",
    name: "Sambal",
    character: "Merah berani tipografi tebal — ayam geprek & pedas-pedasan",
    tags: ["terang", "merah", "berani", "tebal", "pedas"],
    colors: {
      bg: "#FFF8F4",
      surface: "#FFFFFF",
      text: "#261312",
      muted: "#7D615C",
      primary: "#B3261E",
      primaryContrast: "#FFFFFF",
      accent: "#FFC53D",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 26rem at 88% 12%, rgb(255 197 61 / 0.4), transparent 55%), #B3261E",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "0.9rem", button: "0.6rem" },
    layout: { hero: "color-block", menu: "grid-2" },
  },
  kebun: {
    slug: "kebun",
    name: "Kebun",
    character: "Hijau daun natural ringan — healthy food, salad & jus",
    tags: ["terang", "hijau", "natural", "sehat", "ringan"],
    colors: {
      bg: "#F6FBF4",
      surface: "#FFFFFF",
      text: "#233324",
      muted: "#6C7F6C",
      primary: "#3E7C4F",
      primaryContrast: "#FFFFFF",
      accent: "#D9E8C5",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 22rem at 8% 0%, rgb(217 232 197 / 0.6), transparent 60%), linear-gradient(165deg, #EAF5E4 0%, #D8ECD2 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.2rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
  },
  batik: {
    slug: "batik",
    name: "Batik",
    character: "Editorial heritage berpola — resto nusantara & katering hajatan",
    tags: ["terang", "tradisional", "editorial", "heritage", "nusantara", "pola"],
    colors: {
      bg: "#FAF6EE",
      surface: "#FFFFFF",
      text: "#2A2118",
      muted: "#7C6F5E",
      primary: "#3F4C8A",
      primaryContrast: "#FFFFFF",
      accent: "#B98A2F",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(circle at 12% 20%, rgb(185 138 47 / 0.14) 0 18%, transparent 19%), radial-gradient(circle at 88% 75%, rgb(63 76 138 / 0.1) 0 22%, transparent 23%), linear-gradient(170deg, #F5EEDD 0%, #EFE5CE 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 550 },
    radius: { card: "0.5rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "magazine" },
    flair: "batik",
  },
  neon: {
    slug: "neon",
    name: "Neon",
    character: "Gelap menyala khas street food malam — burger, ramen & nongkrong",
    tags: ["gelap", "modern", "menyala", "berani", "malam", "animasi"],
    colors: {
      bg: "#0B0B12",
      surface: "#15151F",
      text: "#EDEDF7",
      muted: "#8E8EA6",
      primary: "#FF3D8A",
      primaryContrast: "#FFFFFF",
      accent: "#22D3EE",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(34rem 22rem at 85% -5%, rgb(255 61 138 / 0.25), transparent 60%), radial-gradient(30rem 20rem at 5% 100%, rgb(34 211 238 / 0.18), transparent 55%), #0B0B12",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "poster", menu: "cards" },
    flair: "neon",
  },
  pasar: {
    slug: "pasar",
    name: "Pasar",
    featured: true,
    character: "Pop berani ala poster pasar — gerobak, jajanan & franchise lokal",
    tags: ["terang", "berani", "pop", "kuning", "brutal", "playful"],
    colors: {
      bg: "#FFD335",
      surface: "#FFFFFF",
      text: "#161311",
      muted: "#5C5344",
      primary: "#161311",
      primaryContrast: "#FFD335",
      accent: "#FF5CA8",
      heroOverlay: "none",
      heroBg: "#FFD335",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "color-block", menu: "polaroid" },
    flair: "brutal",
  },
  kertas: {
    slug: "kertas",
    name: "Kertas",
    character: "Minimal tenang berbingkai — omakase, teh & fine dining kecil",
    tags: ["terang", "minimal", "zen", "tenang", "mewah"],
    colors: {
      bg: "#FBFAF7",
      surface: "#FFFFFF",
      text: "#26241F",
      muted: "#8B857A",
      primary: "#8C2F2F",
      primaryContrast: "#FBFAF7",
      accent: "#C9C2B2",
      heroOverlay: "none",
      heroBg: "#FBFAF7",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.15rem", button: "0.15rem" },
    layout: { hero: "frame", menu: "list" },
    flair: "zen",
  },
  tropis: {
    slug: "tropis",
    name: "Tropis",
    character: "Resort hijau-mangga dengan lengkung — jus bar, poke & brunch",
    tags: ["terang", "hijau", "resort", "lengkung", "segar"],
    colors: {
      bg: "#FBF7EC",
      surface: "#FFFFFF",
      text: "#1D3524",
      muted: "#647A69",
      primary: "#14532D",
      primaryContrast: "#F6FBEF",
      accent: "#F5A623",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 26rem at 90% 8%, rgb(245 166 35 / 0.25), transparent 55%), linear-gradient(160deg, #EFF6E4 0%, #DDEDD2 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 650 },
    radius: { card: "1.5rem", button: "9999px" },
    layout: { hero: "split", menu: "grid-2" },
    flair: "tropis",
  },
  warisan: {
    slug: "warisan",
    name: "Warisan",
    character: "Mewah klasik navy-emas berornamen — hidangan istimewa & hampers",
    tags: ["terang", "mewah", "klasik", "navy", "emas", "ornamen"],
    colors: {
      bg: "#FBF9F4",
      surface: "#FFFFFF",
      text: "#1B2A4A",
      muted: "#6B7690",
      primary: "#1B2A4A",
      primaryContrast: "#F5E9C9",
      accent: "#C9A227",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(34rem 20rem at 50% -8%, rgb(201 162 39 / 0.18), transparent 60%), linear-gradient(170deg, #F7F3E9 0%, #F0E9D8 100%)",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.3rem", button: "0.3rem" },
    layout: { hero: "frame", menu: "magazine" },
    flair: "royal",
  },
  retro: {
    slug: "retro",
    name: "Retro",
    character: "Nuansa 70-an oranye-krem chunky — kedai kopi susu & toast",
    tags: ["terang", "retro", "oranye", "70an", "chunky", "playful"],
    colors: {
      bg: "#FFF6E9",
      surface: "#FFFDF7",
      text: "#4A2C1A",
      muted: "#8A6B52",
      primary: "#E2711D",
      primaryContrast: "#FFF6E9",
      accent: "#FFC15E",
      heroOverlay: "none",
      heroBg:
        "repeating-conic-gradient(from -12deg at 50% 130%, #FFC15E 0deg 9deg, #FFB244 9deg 18deg), radial-gradient(circle at 50% 130%, #FFAD3B 0 40%, transparent 41%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "1.3rem", button: "9999px" },
    layout: { hero: "color-block", menu: "cards" },
    flair: "retro",
  },
  mono: {
    slug: "mono",
    name: "Mono",
    character: "Swiss hitam-putih aksen merah — tegas, grid, tanpa basa-basi",
    tags: ["terang", "minimal", "hitam-putih", "swiss", "tegas"],
    colors: {
      bg: "#FFFFFF",
      surface: "#FFFFFF",
      text: "#111111",
      muted: "#6E6E6E",
      primary: "#111111",
      primaryContrast: "#FFFFFF",
      accent: "#E11D2E",
      heroOverlay: "none",
      heroBg: "#FFFFFF",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "0", button: "0" },
    layout: { hero: "poster", menu: "list" },
    flair: "mono",
  },
  lampion: {
    slug: "lampion",
    name: "Lampion",
    featured: true,
    character: "Merah-emas pecinan hangat — chinese food, dimsum & bakmi",
    tags: ["terang", "merah", "emas", "pecinan", "chinese", "tradisional"],
    colors: {
      bg: "#FDF6EC",
      surface: "#FFFFFF",
      text: "#4A1F1A",
      muted: "#8C6A5D",
      primary: "#8E1F1F",
      primaryContrast: "#F9E8C9",
      accent: "#D9A441",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(16rem 16rem at 15% 0%, rgb(217 164 65 / 0.35), transparent 55%), radial-gradient(20rem 20rem at 90% 15%, rgb(255 120 90 / 0.25), transparent 55%), linear-gradient(170deg, #A32626 0%, #7E1B1B 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "0.9rem", button: "0.5rem" },
    layout: { hero: "color-block", menu: "grid-2" },
    flair: "lampion",
  },
  sketsa: {
    slug: "sketsa",
    name: "Sketsa",
    character: "Papan kapur gelap coretan tangan — angkringan, burjo & kafe santai",
    tags: ["gelap", "unik", "kapur", "santai", "playful"],
    colors: {
      bg: "#22303C",
      surface: "#283947",
      text: "#F1F5F4",
      muted: "#9FB3AD",
      primary: "#FDE68A",
      primaryContrast: "#22303C",
      accent: "#7DD3FC",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 18rem at 85% -5%, rgb(253 230 138 / 0.12), transparent 60%), radial-gradient(24rem 16rem at 5% 100%, rgb(125 211 252 / 0.1), transparent 55%), #1E2A35",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 650 },
    radius: { card: "0.7rem", button: "0.7rem" },
    layout: { hero: "typo", menu: "cards" },
    flair: "sketsa",
  },
  blueprint: {
    slug: "blueprint",
    name: "Blueprint",
    featured: true,
    character: "Cetak biru teknis garis cyan — dapur terbuka & konsep industrial",
    tags: ["gelap", "unik", "teknis", "biru", "industrial"],
    colors: {
      bg: "#10243E",
      surface: "#16304F",
      text: "#EAF4FB",
      muted: "#93AFC5",
      primary: "#7FD1E8",
      primaryContrast: "#0C1C30",
      accent: "#7FD1E8",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 85% 0%, rgb(127 209 232 / 0.14), transparent 60%), #0D1F37",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 700 },
    radius: { card: "0.2rem", button: "0.2rem" },
    layout: { hero: "typo", menu: "magazine" },
    flair: "blueprint",
  },
  koran: {
    slug: "koran",
    name: "Koran",
    character: "Surat kabar klasik hitam-gading — depot legendaris & kuliner lawas",
    tags: ["terang", "klasik", "koran", "editorial", "hitam-putih"],
    colors: {
      bg: "#F7F4EC",
      surface: "#FFFEF9",
      text: "#191714",
      muted: "#6E6A61",
      primary: "#191714",
      primaryContrast: "#F7F4EC",
      accent: "#C0231B",
      heroOverlay: "none",
      heroBg: "#F2EEE3",
    },
    fonts: { heading: FRAUNCES, body: INTER, headingWeight: 700 },
    radius: { card: "0", button: "0" },
    layout: { hero: "typo", menu: "list" },
    flair: "koran",
  },
  aurora: {
    slug: "aurora",
    name: "Aurora",
    character: "Kaca beku bercahaya di kegelapan — dessert bar & speakeasy",
    tags: ["gelap", "mewah", "kaca", "glow", "modern", "animasi"],
    colors: {
      bg: "#0D1022",
      surface: "#171B33",
      text: "#EDEFFB",
      muted: "#9BA2C7",
      primary: "#7C5CFF",
      primaryContrast: "#FFFFFF",
      accent: "#4ADEDE",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(28rem 20rem at 20% 10%, rgb(124 92 255 / 0.3), transparent 60%), radial-gradient(26rem 18rem at 90% 80%, rgb(74 222 222 / 0.2), transparent 55%), #0D1022",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.2rem", button: "9999px" },
    layout: { hero: "split", menu: "cards" },
    flair: "aurora",
  },
  keramik: {
    slug: "keramik",
    name: "Keramik",
    character: "Ubin mediterania kobalt-terakota — resto keluarga & pasta",
    tags: ["terang", "biru", "mediterania", "keramik", "keluarga"],
    colors: {
      bg: "#FDFCF8",
      surface: "#FFFFFF",
      text: "#1E2A44",
      muted: "#64708C",
      primary: "#1D4ED8",
      primaryContrast: "#FFFFFF",
      accent: "#E07A5F",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(circle at 10% 15%, rgb(224 122 95 / 0.25) 0 12%, transparent 13%), radial-gradient(circle at 92% 80%, rgb(255 255 255 / 0.15) 0 15%, transparent 16%), linear-gradient(165deg, #2453DE 0%, #1A44BE 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "0.8rem", button: "0.6rem" },
    layout: { hero: "color-block", menu: "grid-2" },
    flair: "keramik",
  },
  piksel: {
    slug: "piksel",
    name: "Piksel",
    character: "Arcade 8-bit kontras tinggi — gaming cafe & kedai anak muda",
    tags: ["gelap", "unik", "pixel", "arcade", "gaming", "playful"],
    colors: {
      bg: "#101828",
      surface: "#182338",
      text: "#F1F5FB",
      muted: "#93A2BC",
      primary: "#A3E635",
      primaryContrast: "#0F1626",
      accent: "#F471B5",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 16rem at 80% 0%, rgb(244 113 181 / 0.16), transparent 55%), #0D1422",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "0", button: "0" },
    layout: { hero: "poster", menu: "cards" },
    flair: "pixel",
  },
  stempel: {
    slug: "stempel",
    name: "Stempel",
    character: "Kertas kraft & cap karet — kopi manual brew dan roti artisan",
    tags: ["terang", "earth", "kraft", "artisan", "kopi", "unik"],
    colors: {
      bg: "#EFE3CC",
      surface: "#F9F2E3",
      text: "#4A3A26",
      muted: "#8A785F",
      primary: "#4A3A26",
      primaryContrast: "#F5EBD7",
      accent: "#B3402E",
      heroOverlay: "none",
      heroBg: "#EAD9BC",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "frame", menu: "polaroid" },
    flair: "stempel",
  },
  disko: {
    slug: "disko",
    name: "Disko",
    character: "Y2K gradasi panas miring — milkshake, boba & hangout larut",
    tags: ["gelap", "y2k", "gradasi", "playful", "malam", "animasi"],
    colors: {
      bg: "#170B1E",
      surface: "#221230",
      text: "#F7EDFB",
      muted: "#B39BC4",
      primary: "#FF4ECD",
      primaryContrast: "#FFFFFF",
      accent: "#FFB847",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 15% 15%, rgb(255 78 205 / 0.22), transparent 60%), radial-gradient(26rem 18rem at 90% 85%, rgb(255 184 71 / 0.16), transparent 55%), #150A1C",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "1.4rem", button: "9999px" },
    layout: { hero: "poster", menu: "grid-2" },
    flair: "disko",
  },
  hutan: {
    slug: "hutan",
    name: "Hutan",
    character: "Botani gelap mewah emas tipis — fine dining & wine pairing lokal",
    tags: ["gelap", "mewah", "hijau", "botani", "emas", "fine-dining"],
    colors: {
      bg: "#12231A",
      surface: "#1A3024",
      text: "#F2EBDD",
      muted: "#A3B5A3",
      primary: "#B08D3F",
      primaryContrast: "#12231A",
      accent: "#B08D3F",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(32rem 22rem at 80% -5%, rgb(176 141 63 / 0.14), transparent 60%), #0F1E16",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.5rem", button: "0.5rem" },
    layout: { hero: "split", menu: "list" },
    flair: "hutan",
  },
  mentega: {
    slug: "mentega",
    name: "Mentega",
    character: "Kuning mentega lembut menggemaskan — toko kue & sarapan",
    tags: ["terang", "kuning", "lembut", "manis", "bakery", "playful"],
    colors: {
      bg: "#FFFBEB",
      surface: "#FFFFFF",
      text: "#453A1E",
      muted: "#8D8060",
      primary: "#D9A404",
      primaryContrast: "#3C3312",
      accent: "#F6D860",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 26rem at 85% 5%, rgb(246 216 96 / 0.55), transparent 60%), linear-gradient(160deg, #FFF6D6 0%, #FDEDAF 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.5rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
    flair: "krim",
  },
  dermaga: {
    slug: "dermaga",
    name: "Dermaga",
    character: "Pasir-teluk tenang khas tepi laut — kafe pantai & grill ikan",
    tags: ["terang", "pantai", "earth", "tenang", "seafood"],
    colors: {
      bg: "#F4EAD5",
      surface: "#FDF8EC",
      text: "#123A42",
      muted: "#5E7C7E",
      primary: "#0F5B66",
      primaryContrast: "#F4EAD5",
      accent: "#D9822B",
      heroOverlay: "none",
      heroBg: "linear-gradient(180deg, #CFE4E0 0%, #F4EAD5 100%)",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.9rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "list" },
    flair: "ombak",
  },
  kunyit: {
    slug: "kunyit",
    name: "Kunyit",
    character: "Kunyit menyala tipografi raksasa — nasi kuning & masakan rempah",
    tags: ["terang", "oranye", "berani", "tebal", "rempah", "nusantara"],
    colors: {
      bg: "#FFFDF6",
      surface: "#FFFFFF",
      text: "#3D2A10",
      muted: "#8C7250",
      primary: "#D97706",
      primaryContrast: "#FFF9EC",
      accent: "#16803C",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 20rem at 12% 90%, rgb(22 128 60 / 0.2), transparent 55%), linear-gradient(150deg, #F59E0B 0%, #D97706 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.7rem", button: "0.7rem" },
    layout: { hero: "color-block", menu: "magazine" },
    flair: "rempah",
  },
  anggrek: {
    slug: "anggrek",
    name: "Anggrek",
    character: "Ungu anggrek lembut feminin — dessert cantik & tea house",
    tags: ["terang", "ungu", "pastel", "feminin", "lembut", "manis"],
    colors: {
      bg: "#FBF8FF",
      surface: "#FFFFFF",
      text: "#332A44",
      muted: "#83789C",
      primary: "#7C3AED",
      primaryContrast: "#FFFFFF",
      accent: "#F0ABFC",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 24rem at 88% 8%, rgb(240 171 252 / 0.4), transparent 55%), linear-gradient(160deg, #F3E8FF 0%, #E7D4FE 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 550 },
    radius: { card: "1.3rem", button: "9999px" },
    layout: { hero: "typo", menu: "grid-2" },
    flair: "kelopak",
  },
  tanah: {
    slug: "tanah",
    name: "Tanah",
    character: "Lempung monokrom hangat membumi — gerabah, angkringan modern",
    tags: ["terang", "earth", "gerabah", "membumi", "artisan"],
    colors: {
      bg: "#F6EFE8",
      surface: "#FDF9F4",
      text: "#4B2E20",
      muted: "#93755F",
      primary: "#9A4B2F",
      primaryContrast: "#FBF3EC",
      accent: "#D9A583",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #EAD9C9 0%, #DDC2AB 100%)",
    },
    fonts: { heading: FRAUNCES, body: INTER, headingWeight: 600 },
    radius: { card: "1rem", button: "0.6rem" },
    layout: { hero: "split", menu: "cards" },
    flair: "gerabah",
  },
  salju: {
    slug: "salju",
    name: "Salju",
    character: "Es biru putih sebening kaca — gelato, es kopi & minuman dingin",
    tags: ["terang", "biru", "minimal", "dingin", "es", "bersih"],
    colors: {
      bg: "#F6FAFD",
      surface: "#FFFFFF",
      text: "#1E3A50",
      muted: "#6C89A0",
      primary: "#0E6FA8",
      primaryContrast: "#F3FAFF",
      accent: "#BFE3F5",
      heroOverlay: "none",
      heroBg: "#F0F7FC",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 700 },
    radius: { card: "0.9rem", button: "9999px" },
    layout: { hero: "frame", menu: "cards" },
    flair: "beku",
  },
  bara: {
    slug: "bara",
    name: "Bara",
    featured: true,
    character: "Arang membara oranye menyala — sate, bakaran & smoked bbq",
    tags: ["gelap", "oranye", "menyala", "bakaran", "berani", "animasi"],
    colors: {
      bg: "#160F0B",
      surface: "#211712",
      text: "#F7EDE4",
      muted: "#B39A88",
      primary: "#FF6A1F",
      primaryContrast: "#FFFFFF",
      accent: "#FFB347",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 18rem at 50% 110%, rgb(255 106 31 / 0.35), transparent 60%), #120C08",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.8rem", button: "9999px" },
    layout: { hero: "poster", menu: "list" },
    flair: "api",
  },
  pandan: {
    slug: "pandan",
    name: "Pandan",
    character: "Hijau pandan santan lembut — jajan pasar & kue tradisional",
    tags: ["terang", "hijau", "tradisional", "jajan", "lembut"],
    colors: {
      bg: "#F7FBF2",
      surface: "#FFFFFF",
      text: "#2C4025",
      muted: "#7B8F72",
      primary: "#4C8C3F",
      primaryContrast: "#F5FBEF",
      accent: "#DCE8B8",
      heroOverlay: "none",
      heroBg: "linear-gradient(160deg, #E9F3D8 0%, #D3E7BC 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "typo", menu: "polaroid" },
    flair: "anyaman",
  },
  teraso: {
    slug: "teraso",
    name: "Teraso",
    character: "Lantai teraso bertabur warna — kedai es krim & brunch ceria",
    tags: ["terang", "playful", "warna", "teraso", "ceria"],
    colors: {
      bg: "#FBF9F5",
      surface: "#FFFFFF",
      text: "#2B2B2B",
      muted: "#6E6E6E",
      primary: "#E07A5F",
      primaryContrast: "#FFFFFF",
      accent: "#3D5A80",
      heroOverlay: "none",
      heroBg: "#F4F1EA",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "frame", menu: "grid-2" },
    flair: "teraso",
  },
  kabut: {
    slug: "kabut",
    name: "Kabut",
    character: "Abu hangat berkabut aksen blush — brunch tenang & patisserie",
    tags: ["terang", "minimal", "lembut", "sutra", "tenang"],
    colors: {
      bg: "#F3F1EE",
      surface: "#FBFAF8",
      text: "#3A3733",
      muted: "#8B857D",
      primary: "#B0806F",
      primaryContrast: "#FFFFFF",
      accent: "#E5C8BC",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #ECE8E2 0%, #E2DAD1 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "1rem", button: "0.5rem" },
    layout: { hero: "split", menu: "magazine" },
    flair: "sutra",
  },
  jeruk: {
    slug: "jeruk",
    name: "Jeruk",
    featured: true,
    character: "Jeruk pop tebal bergaris hitam — juice bar & rujak modern",
    tags: ["terang", "oranye", "pop", "segar", "berani", "playful"],
    colors: {
      bg: "#FFF8EF",
      surface: "#FFFFFF",
      text: "#1C1408",
      muted: "#6F5C42",
      primary: "#FF7A00",
      primaryContrast: "#FFFFFF",
      accent: "#57C750",
      heroOverlay: "none",
      heroBg: "#FF8F1F",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.9rem", button: "9999px" },
    layout: { hero: "color-block", menu: "polaroid" },
    flair: "segar",
  },
  merak: {
    slug: "merak",
    name: "Merak",
    character: "Teal merak berhias emas — resto peranakan & seafood premium",
    tags: ["terang", "mewah", "teal", "emas", "peranakan"],
    colors: {
      bg: "#F6F7F2",
      surface: "#FFFFFF",
      text: "#0C4A50",
      muted: "#5E8489",
      primary: "#0C4A50",
      primaryContrast: "#EFD9A7",
      accent: "#C9A227",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(28rem 18rem at 85% 0%, rgb(201 162 39 / 0.2), transparent 55%), linear-gradient(165deg, #0F565D 0%, #093B41 100%)",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.6rem", button: "0.4rem" },
    layout: { hero: "color-block", menu: "magazine" },
    flair: "bulu",
  },
  sinar: {
    slug: "sinar",
    name: "Sinar",
    character: "Cahaya sore keemasan bergerak pelan — rumah makan sore & kopi senja",
    tags: ["terang", "emas", "hangat", "animasi", "lembut"],
    colors: {
      bg: "#FFF9EE",
      surface: "#FFFFFF",
      text: "#3E2E14",
      muted: "#8A7657",
      primary: "#E8A020",
      primaryContrast: "#3B2B0E",
      accent: "#FFD989",
      heroOverlay: "none",
      heroBg: "linear-gradient(120deg, #FFEFC9 0%, #FFDD9A 45%, #FFC96B 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
    flair: "sinar",
  },
  kunang: {
    slug: "kunang",
    name: "Kunang",
    featured: true,
    character: "Malam hutan dengan kunang-kunang melayang — dinner outdoor & taman",
    tags: ["gelap", "hijau", "malam", "animasi", "romantis"],
    colors: {
      bg: "#101C14",
      surface: "#17271C",
      text: "#EAF2E6",
      muted: "#9AAF9C",
      primary: "#C6F432",
      primaryContrast: "#14200F",
      accent: "#FFE066",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 80% 0%, rgb(198 244 50 / 0.1), transparent 60%), #0C160F",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "0.9rem", button: "9999px" },
    layout: { hero: "typo", menu: "list" },
    flair: "kunang",
  },
  uap: {
    slug: "uap",
    name: "Uap",
    character: "Kepulan uap kopi hangat naik perlahan — kedai kopi tenang",
    tags: ["terang", "kopi", "earth", "tenang", "animasi"],
    colors: {
      bg: "#F3EDE5",
      surface: "#FCF8F2",
      text: "#443A2E",
      muted: "#8B7D6C",
      primary: "#7A5C43",
      primaryContrast: "#F7F0E6",
      accent: "#C9B394",
      heroOverlay: "none",
      heroBg: "#EFE7DB",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.8rem", button: "0.5rem" },
    layout: { hero: "frame", menu: "magazine" },
    flair: "uap",
  },
  denyut: {
    slug: "denyut",
    name: "Denyut",
    character: "Detak neon mint di kegelapan — bar jus sehat & gym cafe",
    tags: ["gelap", "mint", "menyala", "modern", "animasi", "sehat"],
    colors: {
      bg: "#0A1418",
      surface: "#122029",
      text: "#E8F6F4",
      muted: "#8FAAA6",
      primary: "#2DE1C2",
      primaryContrast: "#06211C",
      accent: "#B8F135",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(28rem 18rem at 50% -10%, rgb(45 225 194 / 0.16), transparent 60%), #081115",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 800 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "poster", menu: "grid-2" },
    flair: "denyut",
  },
  melayang: {
    slug: "melayang",
    name: "Melayang",
    character: "Kartu mengambang pelan di langit pastel — dessert ringan & pastry",
    tags: ["terang", "pastel", "biru", "lembut", "animasi", "playful"],
    colors: {
      bg: "#F2F7FF",
      surface: "#FFFFFF",
      text: "#2C3A55",
      muted: "#7C8AA5",
      primary: "#5B8DEF",
      primaryContrast: "#FFFFFF",
      accent: "#FFC9DE",
      heroOverlay: "none",
      heroBg: "linear-gradient(180deg, #DCEBFF 0%, #F2F7FF 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.3rem", button: "9999px" },
    layout: { hero: "split", menu: "cards" },
    flair: "melayang",
  },
  tinta: {
    slug: "tinta",
    name: "Tinta",
    character: "Sapuan kuas tinta dengan garis merah tergores — ramen & izakaya",
    tags: ["terang", "minimal", "jepang", "kuas", "animasi"],
    colors: {
      bg: "#FAFAF7",
      surface: "#FFFFFF",
      text: "#171715",
      muted: "#6B6B66",
      primary: "#171715",
      primaryContrast: "#FAFAF7",
      accent: "#D43D2A",
      heroOverlay: "none",
      heroBg: "#F4F4EF",
    },
    fonts: { heading: FRAUNCES, body: INTER, headingWeight: 700 },
    radius: { card: "0.3rem", button: "0.3rem" },
    layout: { hero: "typo", menu: "list" },
    flair: "tinta",
  },
  prisma: {
    slug: "prisma",
    name: "Prisma",
    character: "Holografik lembut berputar warna — gelato artisan & dessert lab",
    tags: ["terang", "pastel", "holografik", "modern", "animasi"],
    colors: {
      bg: "#FDFCFF",
      surface: "#FFFFFF",
      text: "#33304A",
      muted: "#807C99",
      primary: "#8B5CF6",
      primaryContrast: "#FFFFFF",
      accent: "#5EEAD4",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 20rem at 15% 15%, rgb(139 92 246 / 0.18), transparent 55%), radial-gradient(24rem 18rem at 88% 80%, rgb(94 234 212 / 0.2), transparent 55%), #FBFAFF",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.2rem", button: "9999px" },
    layout: { hero: "split", menu: "grid-2" },
    flair: "prisma",
  },
  loket: {
    slug: "loket",
    name: "Loket",
    featured: true,
    character: "Marquee bioskop lawas berlampu berlari — snack bar & cinema cafe",
    tags: ["gelap", "retro", "bioskop", "merah", "animasi", "playful"],
    colors: {
      bg: "#1D0F12",
      surface: "#2A171B",
      text: "#F7E9DC",
      muted: "#B39A94",
      primary: "#E8433F",
      primaryContrast: "#FFFFFF",
      accent: "#FFC94A",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(26rem 16rem at 50% -8%, rgb(232 67 63 / 0.2), transparent 60%), #180C0F",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "0.8rem", button: "0.6rem" },
    layout: { hero: "poster", menu: "polaroid" },
    flair: "loket",
  },
  sawah: {
    slug: "sawah",
    name: "Sawah",
    featured: true,
    character: "Terasering hijau bergoyang angin — nasi liwet & masakan desa",
    tags: ["terang", "hijau", "desa", "natural", "animasi"],
    colors: {
      bg: "#F4FAEE",
      surface: "#FFFFFF",
      text: "#27401F",
      muted: "#748A6B",
      primary: "#4F8A2E",
      primaryContrast: "#F6FBEF",
      accent: "#8FD14F",
      heroOverlay: "none",
      heroBg: "linear-gradient(180deg, #DFF0FA 0%, #EAF5DC 60%, #D8ECC2 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
    flair: "sawah",
  },
  kilau: {
    slug: "kilau",
    name: "Kilau",
    character: "Emas sampanye berkilau menyapu judul — omakase & tasting menu",
    tags: ["gelap", "mewah", "emas", "shimmer", "animasi", "fine-dining"],
    colors: {
      bg: "#17150F",
      surface: "#211E15",
      text: "#F0E9DA",
      muted: "#A99F8A",
      primary: "#D4AF37",
      primaryContrast: "#171407",
      accent: "#F5E2A8",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 18rem at 50% -10%, rgb(212 175 55 / 0.14), transparent 60%), #131109",
    },
    fonts: { heading: MARCELLUS, body: JAKARTA, headingWeight: 400 },
    radius: { card: "0.4rem", button: "0.4rem" },
    layout: { hero: "frame", menu: "magazine" },
    flair: "kilau",
  },
  gelembung: {
    slug: "gelembung",
    name: "Gelembung",
    character: "Gelembung boba naik pelan, hover memantul — kedai boba & milk bar",
    tags: ["terang", "boba", "coklat", "manis", "animasi", "playful"],
    colors: {
      bg: "#FFF7F0",
      surface: "#FFFFFF",
      text: "#4A322B",
      muted: "#94796C",
      primary: "#B4743F",
      primaryContrast: "#FFF6EC",
      accent: "#F3C5A0",
      heroOverlay: "none",
      heroBg: "linear-gradient(160deg, #C88A52 0%, #A96B38 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1.5rem", button: "9999px" },
    layout: { hero: "color-block", menu: "grid-2" },
    flair: "gelembung",
  },
  lilin: {
    slug: "lilin",
    name: "Lilin",
    featured: true,
    character: "Cahaya lilin berkedip hangat bernapas — dinner romantis & steak",
    tags: ["gelap", "romantis", "hangat", "lilin", "animasi", "malam"],
    colors: {
      bg: "#191410",
      surface: "#231C15",
      text: "#F5EADB",
      muted: "#B3A38E",
      primary: "#E89B3C",
      primaryContrast: "#1E1610",
      accent: "#FFD9A0",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 16rem at 50% 105%, rgb(232 155 60 / 0.22), transparent 60%), #140F0B",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 550 },
    radius: { card: "0.8rem", button: "9999px" },
    layout: { hero: "typo", menu: "list" },
    flair: "lilin",
  },
  orbit: {
    slug: "orbit",
    name: "Orbit",
    character: "Angkasa playful bintang berkedip — kedai malam & 24 jam",
    tags: ["gelap", "angkasa", "playful", "bintang", "animasi", "malam"],
    colors: {
      bg: "#12122B",
      surface: "#1B1B3D",
      text: "#EEEEFA",
      muted: "#9C9CC0",
      primary: "#FF6B6B",
      primaryContrast: "#FFFFFF",
      accent: "#6BE4FF",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(30rem 20rem at 85% -5%, rgb(107 228 255 / 0.12), transparent 60%), #0E0E24",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "1.1rem", button: "9999px" },
    layout: { hero: "poster", menu: "cards" },
    flair: "orbit",
  },
  gugur: {
    slug: "gugur",
    name: "Gugur",
    character: "Daun musim gugur melayang jatuh — kedai teh & roastery",
    tags: ["terang", "earth", "musim-gugur", "hangat", "animasi"],
    colors: {
      bg: "#FBF3E9",
      surface: "#FFFCF7",
      text: "#4C2E1C",
      muted: "#94765F",
      primary: "#C05621",
      primaryContrast: "#FFF6ED",
      accent: "#E9B44C",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #F6E3C8 0%, #EDD0A8 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 600 },
    radius: { card: "0.9rem", button: "0.6rem" },
    layout: { hero: "split", menu: "magazine" },
    flair: "gugur",
  },
  sirup: {
    slug: "sirup",
    name: "Sirup",
    character: "Blob sirup permen bermorf pelan — es campur & dessert manis",
    tags: ["terang", "pink", "manis", "permen", "animasi", "playful"],
    colors: {
      bg: "#FFF4F7",
      surface: "#FFFFFF",
      text: "#47243A",
      muted: "#96718A",
      primary: "#E84393",
      primaryContrast: "#FFFFFF",
      accent: "#74D3AE",
      heroOverlay: "none",
      heroBg: "linear-gradient(150deg, #F368AB 0%, #D63384 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "1.4rem", button: "9999px" },
    layout: { hero: "color-block", menu: "polaroid" },
    flair: "sirup",
  },
  jendela: {
    slug: "jendela",
    name: "Jendela",
    character: "Berkas cahaya pagi menyapu ruangan — brunch terang & toko roti",
    tags: ["terang", "minimal", "cahaya", "tenang", "animasi"],
    colors: {
      bg: "#FCFBF7",
      surface: "#FFFFFF",
      text: "#3B372E",
      muted: "#8A8375",
      primary: "#A87C4F",
      primaryContrast: "#FFFDF8",
      accent: "#E5D9C0",
      heroOverlay: "none",
      heroBg: "linear-gradient(170deg, #F7F3EA 0%, #EFE7D7 100%)",
    },
    fonts: { heading: MARCELLUS, body: INTER, headingWeight: 400 },
    radius: { card: "0.9rem", button: "0.5rem" },
    layout: { hero: "frame", menu: "list" },
    flair: "jendela",
  },
  komet: {
    slug: "komet",
    name: "Komet",
    character: "Bintang jatuh melintas sesekali — mie malam & wedangan",
    tags: ["gelap", "biru", "malam", "bintang", "animasi"],
    colors: {
      bg: "#0B1026",
      surface: "#141A38",
      text: "#E9EDFB",
      muted: "#94A0C4",
      primary: "#4F7CFF",
      primaryContrast: "#FFFFFF",
      accent: "#9BE8FF",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(28rem 18rem at 20% -8%, rgb(79 124 255 / 0.18), transparent 60%), #080D20",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 700 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "typo", menu: "cards" },
    flair: "komet",
  },
  angin: {
    slug: "angin",
    name: "Angin",
    character: "Sage sejuk kartu miring tertiup lembut — salad bar & poke sehat",
    tags: ["terang", "hijau", "sage", "sehat", "animasi", "lembut"],
    colors: {
      bg: "#F3F7F1",
      surface: "#FFFFFF",
      text: "#334430",
      muted: "#7E8F7A",
      primary: "#6A9955",
      primaryContrast: "#F6FBF2",
      accent: "#CBE3B8",
      heroOverlay: "none",
      heroBg: "linear-gradient(165deg, #E7F0E1 0%, #D7E6CC 100%)",
    },
    fonts: { heading: FRAUNCES, body: JAKARTA, headingWeight: 550 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "split", menu: "cards" },
    flair: "angin",
  },
  aksara: {
    slug: "aksara",
    name: "Aksara",
    character: "Tagline mengetik sendiri gaya editor — kedai buku & kopi",
    tags: ["terang", "minimal", "ketik", "editorial", "animasi", "unik"],
    colors: {
      bg: "#FBFAF4",
      surface: "#FFFFFF",
      text: "#22304A",
      muted: "#6F7A90",
      primary: "#22304A",
      primaryContrast: "#FBFAF4",
      accent: "#3B82F6",
      heroOverlay: "none",
      heroBg: "#F4F2E9",
    },
    fonts: { heading: BRICOLAGE, body: INTER, headingWeight: 700 },
    radius: { card: "0.5rem", button: "0.5rem" },
    layout: { hero: "typo", menu: "magazine" },
    flair: "aksara",
  },
  karnaval: {
    slug: "karnaval",
    name: "Karnaval",
    featured: true,
    character: "Bendera pesta berkibar warna-warni — jajanan pasar malam & festival",
    tags: ["terang", "merah", "festival", "bendera", "animasi", "playful"],
    colors: {
      bg: "#FFFBEF",
      surface: "#FFFFFF",
      text: "#33203A",
      muted: "#7E6B85",
      primary: "#E9484A",
      primaryContrast: "#FFFFFF",
      accent: "#2EB8A6",
      heroOverlay: "none",
      heroBg:
        "radial-gradient(24rem 18rem at 85% 90%, rgb(46 184 166 / 0.25), transparent 55%), linear-gradient(155deg, #F0565A 0%, #D93C48 100%)",
    },
    fonts: { heading: BRICOLAGE, body: JAKARTA, headingWeight: 800 },
    radius: { card: "1rem", button: "9999px" },
    layout: { hero: "color-block", menu: "polaroid" },
    flair: "karnaval",
  },
};

export const DEFAULT_THEME = "hangat";

export const FEATURED_THEME_SLUGS = [
  "lampion",
  "pasar",
  "karnaval",
  "blueprint",
  "bara",
  "loket",
  "lilin",
  "sawah",
  "kunang",
  "jeruk",
] as const;

export const FEATURED_DEMO_THEME = FEATURED_THEME_SLUGS[0];

export function themeConfigFor(slug: string): ThemeConfig {
  return KULINER_THEMES[slug] ?? (KULINER_THEMES[DEFAULT_THEME] as ThemeConfig);
}

export function isFeaturedTheme(slug: string): boolean {
  return KULINER_THEMES[slug]?.featured === true;
}

export function featuredThemes(): ThemeConfig[] {
  return FEATURED_THEME_SLUGS.map((slug) => KULINER_THEMES[slug] as ThemeConfig);
}

export function themeSwatch(config: ThemeConfig): { gradient: string; textColor: string } {
  const { bg, accent, primary, text } = config.colors;
  return {
    gradient: `linear-gradient(135deg, ${bg} 0%, ${accent} 60%, ${primary} 115%)`,
    textColor: text,
  };
}
